### ISSUE TITLE
namespace expandable_selector

### ISSUE THREAD

**Issue by jrodriguezpuigvert** [Karumi/ExpandableSelector#4]
Hi everyone! 
 I can access to expandable_selector namespace from the library sample. However, the same sample used in on a new project is not working as expected. Importing the library using gradle instructions, this namespace is inaccesible.

**Comment by pedrovgs** [comment]
Hey @jrodriguezpuigvert I was taking a look to this issue? Why have you closed it?

**Comment by pedrovgs** [comment]
@jrodriguezpuigvert I've created a new project, import the library, add the widget to an activity, configure the theme and some sample data and the library is working as should :(

**Comment by jrodriguezpuigvert** [comment]
Hi It was not an issue of the library. To access to corresponding namespace, in the xml has to be defined as follows : 
xmlns:expandable_selector= "http://schemas.android.com/apk/lib/com.karumi.expandableselector"

Using :     xmlns:expandable_selector="http://schemas.android.com/apk/res-auto"
Android Studio is not able to find anything in this path.

I thought that the namespace will be accesible from res-auto but is not.

**Comment by pedrovgs** [comment]
The README.md explains how to add some customizable elements but the namespace is missing. I'm going to update it with the namespace information. Thanks for your feedback!

**Comment by jrodriguezpuigvert** [comment]
You are welcome. This library works really great! Excellent work!

**Comment by pedrovgs** [comment]
Thanks! Are you going to use it in any project?

**Comment by jrodriguezpuigvert** [comment]
Maybe, at the moment I am testing features of Material design.

 Sorry but I think that you have to edit again Readme.md specifying
 xmlns:expandable_selector= "http://schemas.android.com/apk/lib/com.karumi.expandableselector"

otherwise Android Studio doesn't find the namespace.

**Comment by pedrovgs** [comment]
The sample and the project I've created are working with this namespace: `xmlns:expandable_selector="http://schemas.android.com/apk/res-auto"` If you use the other namespace the configuration is not going to be applied to the widget. The code is going to compile, but the configuration is not going to be applied.
